// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_config/flutter_config.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8ULnpSBdyZZuN8unfSgNCnWDB4DXpkJQ',
    appId: '1:1025422084398:web:f88ed66b2176919a3912bf',
    messagingSenderId: '1025422084398',
    projectId: 'testdb-1de69',
    authDomain: 'testdb-1de69.firebaseapp.com',
    storageBucket: 'testdb-1de69.appspot.com',
    measurementId: 'G-2E99V1QTKW',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvMAqoWHKPZprmFiYdX-4agk5-u9SYbuU',
    appId: '1:1025422084398:ios:85050fa4f3891d013912bf',
    messagingSenderId: '1025422084398',
    projectId: 'testdb-1de69',
    storageBucket: 'testdb-1de69.appspot.com',
    iosClientId:
        '1025422084398-vfkg5td23tsse59mvqcejg1cum4g6rc5.apps.googleusercontent.com',
    iosBundleId: 'com.example.memzClone',
  );
}
